#!/bin/bash


clam_status(){

	clamav=`sudo systemctl status clamav`
	clamav_db=`sudo systemctl status clamav-freshclam`

	zenity --list \
		--column "ClamAV and FreshClam Status" \
		 --width 900 \
		 --height 500 \
		 "$clamav"  \ 
		 "$clamav_db" 

menu

}


scan(){

	# Scan With clamAV
	

	sudo clamscan --infected --recursive --remove /


	# Scan Rootkits with RKhunetr
	
	sudo rkhunter -c

	# Maldet

	maldet -a /


menu

}








update(){

		# clamAV
		sudo freshclam

	
		# RKhunter
		/usr/local/bin/rkhunter --update 
		/usr/local/bin/rkhunter --propupd



		# Malware Detect
		sudo /usr/local/sbin/maldet --mkpubpaths



menu
}




menu(){
	choice=`zenity --info --title 'KYGnus' \
		--text 'KYGnus Scan System' \
		--ok-label OK \
		--extra-button Scan \
		--extra-button Update \
		--extra-button Status \
		--extra-button Exit \
		--width 400 \
		--height 100`

	if [ "$choice" == Scan ];then
		scan
	elif [ "$choice" == Update ];then
		update
	elif [ "$choice" == Exit ];then
		exit 0
	elif [ "$choice" == Status ];then
		clam_status
	else
		menu
	fi
}


menu
