#!/bin/bash


clam_status(){

	clamav=`sudo systemctl status clamav`
	clamav_db=`sudo systemctl status clamav-freshclam`

	zenity --list \
		--column "Openssh Server Status" \
		 --width 900 \
		 --height 500 \
		 "$clamav"  \ 
		 "$clamav_db" 

menu

}


scan_local(){

	# Scan With clamAV
	

	sudo clamscan --infected --recursive --remove /


	# Scan Rootkits with RKhunetr
	
	sudo rkhunter -c

	# Maldet

	maldet -a /


}




scan_remote(){



	# Scan With clamAV
	

	ssh -t $user@$ip  sudo clamscan --infected --recursive --remove /


	# Scan Rootkits with RKhunetr
	
	ssh -t $user@$ip sudo rkhunter -c

	# Maldet

	 ssh -t $user@$ip maldet -a /




}




updatelocal(){

		# clamAV
		sudo freshclam

	
		# RKhunter
		/usr/local/bin/rkhunter --update 
		/usr/local/bin/rkhunter --propupd



		# Malware Detect
		sudo /usr/local/sbin/maldet --mkpubpaths
}


update_remote(){

		# clamAV
		ssh -t $user@$ip sudo freshclam

	
		# RKhunter
		ssh -t $user@$ip /usr/local/bin/rkhunter --update 
		ssh -t $user@$ip /usr/local/bin/rkhunter --propupd



		# Malware Detect
		ssh -t $user@$ip sudo /usr/local/sbin/maldet --mkpubpaths




}


menu(){
	choice=`zenity --info --title 'KYGnus' \
		--text 'KYGnus Scan System' \
		--ok-label OK \
		--extra-button ScanLocal \
		--extra-button ScanRemote \
		--extra-button UpdateLocal \
		--extra-button UpdateRemote \
		--extra-button Status \
		--extra-button Exit \
		--width 600 \
		--height 100`

	if [ "$choice" == ScanLocal ];then
		scan_local
	elif [ "$choice" == ScanRemote ];then
		scan_remote
	elif [ "$choice" == UpdateLocal ];then
		update_local
	elif [ "$choice" == Exit ];then
		exit 0
	elif [ "$choice" == UpdateRemote ];then
		update_remote
	elif [ "$choice" == Status ];then
		clam_status
	else
		menu
	fi
}


menu
